# ********************************************************************************
#  Copyright (c) 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

name: Check 3rd party dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
    - "Cargo.*"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deps:
    name: "Check 3rd party licenses"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo tree
      working-directory: ${{github.workspace}}
      run: |
        cargo tree -e normal --prefix none --no-dedupe \
          | sort -u \
          | grep -v '^[[:space:]]*$' \
          | grep -v uprotocol-sdk \
          | sed -E 's|([^ ]+) v([^ ]+).*|crate/cratesio/-/\1/\2|' \
          > DEPS.txt
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
    - name: "Download latest Dash jar file"
      working-directory: ${{github.workspace}}
      run: |
        wget -O dash.jar "https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST"
    - name: "Run latest Eclipse Dash jar file"
      working-directory: ${{github.workspace}}
      continue-on-error: true
      run: |
        wget -O dash.jar "https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST"
        java -Dorg.eclipse.dash.timeout=60 -jar dash.jar -batch 90 -summary DEPENDENCIES.txt DEPS.txt
    - name: Upload DEPENDENCIES file
      uses: actions/upload-artifact@v4
      with:
        name: 3rd-party-dependencies
        path: DEPENDENCIES.txt
