# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Verifies that this crate can be built using the uProtocol Core API from up-spec's main branch.
# Also performs requirements tracing using OpenFastTrace. The job fails if any of the two
# activities fail.

name: uP Spec Compatibility

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  RUST_TOOLCHAIN: ${{ vars.RUST_TOOLCHAIN || 'stable' }}
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  up-spec-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Fast-Forward to HEAD revision of uProtocol Spec main branch
        run: |
          cd "${{ github.workspace }}/up-spec"
          echo "Switching to up-spec/main branch ..."
          git checkout main
          echo "fast-forwarding to HEAD revision ..."
          git pull
          git status
          cd "${{ github.workspace }}"

      # run OpenFastTrace first because the action will always succeed and produce
      # a tracing report
      - name: Run OpenFastTrace
        id: run-oft
        uses: eclipse-uprotocol/ci-cd/.github/actions/run-oft@main
        with:
          file-patterns: "${{ vars.UP_SPEC_OPEN_FAST_TRACE_FILE_PATTERNS }} ${{ vars.UP_COMPONENT_OPEN_FAST_TRACE_FILE_PATTERNS }}"
          tags: "_,LanguageLibrary"

      # now try to build and run the tests which may fail if incomaptible changes
      # have been introduced into the uProtocol Core API
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: |
          # Using nextest because it's faster than built-in test
          cargo nextest run --all-features
          # but it cannot execute doc tests
          cargo test --doc --all-features

      # This step will only be run if the tests in the previous step have succeeded.
      # In that case, we use the exit code produced by the OFT run as the job's
      # overall outcome. This means that the job fails if the tests run successfully
      # but some of the requirements from up-spec are not covered.
      - name: Determine exit status
        env:
          OFT_EXIT_CODE: ${{ steps.run-oft.outputs.oft-exit-code }}
        run: |
          exit $OFT_EXIT_CODE
