# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Perform requirements tracing against the uProtocol Specification using OpenFastTrace (https://github.com/itsallcode/openfasttrace)
# Upload tracing report for potential re-use in publication workflow, returns the corresponding download URL as an output on workflow_call

name: Requirements tracing

on:
  workflow_call:
    outputs:
      tracing_report_url:
        description: 'URL of the requirements tracing report'
        value: ${{ jobs.tracing.outputs.requirements-tracing-report-url }}
  workflow_dispatch:
  pull_request:

env:
  OFT_REPO_BASE: "https://github.com/itsallcode"
  OFT_CORE_VERSION: "4.1.0"
  OFT_ASCIIDOC_PLUGIN_VERSION: "0.2.0"
  TRACING_REPORT_FILE_NAME: "requirements-tracing-report.html"
          
jobs:
  tracing:
    name: Run OpenFastTrace
    runs-on: ubuntu-latest
    outputs:
      requirements-tracing-report-url: ${{ steps.tracing-report-html.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Download OpenFastTrace JARs
        run: |
          mkdir "${{ github.workspace }}/lib"
          curl -L -o "${{ github.workspace }}/lib/openfasttrace.jar" \
            "${{ env.OFT_REPO_BASE }}/openfasttrace/releases/download/${{ env.OFT_CORE_VERSION }}/openfasttrace-${{ env.OFT_CORE_VERSION }}.jar"
          curl -L -o "${{ github.workspace }}/lib/openfasttrace-asciidoc-plugin.jar" \
            "${{ env.OFT_REPO_BASE }}/openfasttrace-asciidoc-plugin/releases/download/${{ env.OFT_ASCIIDOC_PLUGIN_VERSION }}/openfasttrace-asciidoc-plugin-${{ env.OFT_ASCIIDOC_PLUGIN_VERSION }}-with-dependencies.jar"
      - name: Run OpenFastTrace
        id: run-oft
        shell: bash
        run: |
          if java -cp "${{ github.workspace }}/lib/*" \
            org.itsallcode.openfasttrace.core.cli.CliStarter trace -o html \
            -f "${{ env.TRACING_REPORT_FILE_NAME }}" \
            *.md \
            *.rs \
            .github \
            examples \
            src \
            tests \
            tools \
            up-spec/*.adoc \
            up-spec/*.md \
            up-spec/basics \
            up-spec/up-l1/README.* \
            up-spec/up-l2 \
            up-spec/up-l3;
          then
            echo "requirements-tracing-exit-code=0" >> $GITHUB_OUTPUT
            echo "All requirements from uProtocol Specification are covered by crate." >> $GITHUB_STEP_SUMMARY
          else
            echo "requirements-tracing-exit-code=1" >> $GITHUB_OUTPUT
            echo "Some requirements from uProtocol Specification are not covered by crate. See attached report for details." >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: Upload tracing report (html)
        uses: actions/upload-artifact@v4
        id: tracing-report-html
        with:
          name: tracing-report-html
          path: ${{ env.TRACING_REPORT_FILE_NAME }}

      - name: "Determine exit code"
        run: |
          exit ${{ steps.run-oft.outputs.requirements-tracing-exit-code }}
